In [1]:
import torch
import triton
import triton.language as tl

In [2]:
7//2

3

In [7]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
print(a[:, None]*2)
print(b[None, :])
a[:, None]*2 + b[None, :]

tensor([[2],
        [4],
        [6]])
tensor([[4, 5, 6]])


tensor([[ 6,  7,  8],
        [ 8,  9, 10],
        [10, 11, 12]])

In [3]:
assert 1==1, "矩阵维度不匹配，无法相乘"

In [6]:
import torch
offs_m=torch.Tensor([1,2,3,4])
current_k_offsets=torch.Tensor([5,6,7,8])
(offs_m[:, None] < 3) & (current_k_offsets[None, :] < 6)

tensor([[ True, False, False, False],
        [ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])