In [2]:
import torch

mask_matrix=torch.tril(torch.ones(3,3))
a=torch.randn(3,3)
a=a.masked_fill(mask_matrix==1,float('-inf'))
a

tensor([[      -inf, 1.0189e-03, 1.2305e+00],
        [      -inf,       -inf, 5.4534e-01],
        [      -inf,       -inf,       -inf]])

In [ ]:
b=torch.int(1024)
b=torch.sqrt(torch.Tensor([1024]))


tensor([32.])

In [8]:
b.to(dtype=torch.float32)
b

tensor([32.])

In [18]:
c=torch.randint(1024,(1,))
d=torch.sqrt(c)
d.type()

'torch.FloatTensor'

In [ ]:
a=1
type(a)



tensor([6.0117e-32])

In [26]:
t3 = torch.tensor(3, dtype=torch.float32) 
t3

tensor(3.)

In [29]:
import math
a=torch.Tensor([1,2,3])
a-1
# math.exp(a-1)/10

tensor([0., 1., 2.])

In [32]:
torch.exp(a-1)/10

tensor([0.1000, 0.2718, 0.7389])

In [33]:
Q=torch.randn(5,768)
seq_len,embed_dim=Q.shape
print(seq_len,embed_dim)

5 768


In [37]:
a=float("-inf")
b=torch.Tensor([1])
b.item()
max(a,b)

tensor([1.])

In [5]:
(6+3-1)//3

2

In [7]:
import torch
a=torch.Tensor([[[1],[2],[3]]])
a

tensor([[[1.],
         [2.],
         [3.]]])

In [25]:
X=torch.Tensor([[1,2,3,4],[0,0,1,1],[1,1,2,2]])
b=torch.maximum(a, X)
print(b.shape)
print(b)

torch.Size([1, 3, 4])
tensor([[[1., 2., 3., 4.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])


In [36]:
c=torch.max(b,dim=2)
c.values[0]


tensor([4., 2., 3.])

In [19]:
torch.ones(4)*float("-inf")

tensor([-inf, -inf, -inf, -inf])

In [32]:
e=torch.Tensor([1.,2.,3.])
e

tensor([1., 2., 3.])

In [40]:
f=torch.stack([c.values[0], e], dim=0)
f

tensor([[4., 2., 3.],
        [1., 2., 3.]])

In [39]:
torch.max(f,dim=0)

torch.return_types.max(
values=tensor([4., 2., 3.]),
indices=tensor([0, 0, 0]))

In [41]:
a=torch.Tensor([[1],[2],[3]])
a

tensor([[1.],
        [2.],
        [3.]])

In [42]:
b=torch.Tensor([[1,2],[2,3],[3,4]])
b-a

tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])

In [48]:
a=a.view(1,3)
a

tensor([[1., 2., 3.]])

In [46]:
a.size()

torch.Size([3, 1])

In [53]:
torch.empty((2,3))

tensor([[2.4324e-31, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])